// Full virtual keyboard, drawn directly into the framebuffer. Header-only: no
// VitaSDK dependency, no syscalls, no locks, no allocation — which is what
// lets it be compiled and tested on the host (tools/tests/kb_test.cpp) even
// though the actual display path only runs on console.
//
// The system keyboard (SceIme / sceCommonDialogUpdate) isn't used because it
// requires an initialized sceGxm, a color surface, and a sync object advanced
// via sceGxmDisplayQueueAddEntry. The default display path (vita_present.cpp)
// has neither — it sets a CDRAM memblock via sceDisplaySetFrameBuf — and that
// is exactly the path used for the login menu (account/password entry). The
// system dialog is therefore structurally unavailable there, and restricting
// it to the one mode where its contract holds (D2_GXMASYNC=1) would still let
// the dialog's GPU writes and the overlay's CPU writes race on the same
// buffer with no guaranteed order.
//
// Model: the input tick (game thread) writes state; the presentation thread
// reads it to draw. Same benign races as the frame counter — display only,
// never game state.
//
// Security: the local echo (what was just typed) lets the user re-read their
// input; in masked mode it renders as dots. It is never passed to a log
// function, and is cleared on close.
#ifndef D2VITA_VITA_KB_H
#define D2VITA_VITA_KB_H

#include <stdint.h>
#include <string.h>

namespace d2kb {

// --- 8x16 font, ASCII 32..126 ------------------------------------------------
// Generated by tools/kb_font_gen.py (DejaVu Sans Mono rendered then
// thresholded, plus a few manual touch-ups listed in the generator). Do not
// edit here — regenerate instead.
#include "vita_kb_font.h"

inline const unsigned char* glyph(char ch) {
    const unsigned c = (unsigned char)ch;
    if (c < 32u || c > 126u) return 0;
    return g_kb_font95[c - 32u];
}

// --- actions ----------------------------------------------------------------
enum Act { ACT_NONE = 0, ACT_CHAR, ACT_SPACE, ACT_BACK, ACT_ENTER,
           ACT_SHIFT, ACT_MASK, ACT_CLOSE };

// --- layout -------------------------------------------------------------------
// The four character rows cover the entire printable ASCII range (32..126):
// 94 glyphs across 47 cells x 2 (lowercase/uppercase), plus space as its own
// key. The host test verifies this character by character.
struct Layout {
    const char*   lo[4];      // key faces, shift released
    const char*   up[4];      // key faces, shift engaged
    int           nrows;      // character rows
    const char*   fn[8];      // function row labels
    unsigned char fnact[8];   // action for each function key
    int           nfn;
    int           echo;       // 1 = has a local echo line
    const char*   name;
};

static const Layout LAY_FULL = {
    { "1234567890-=", "qwertyuiop[]", "asdfghjkl;'\\", "zxcvbnm,./`" },
    { "!@#$%^&*()_+", "QWERTYUIOP{}", "ASDFGHJKL:\"|", "ZXCVBNM<>?~" },
    4,
    { "maj", "espace", "effacer", "entree", "masque", "fermer" },
    { ACT_SHIFT, ACT_SPACE, ACT_BACK, ACT_ENTER, ACT_MASK, ACT_CLOSE },
    6, 1, "complet"
};

// Legacy layout, kept available under D2_KBSIMPLE=1 as a fallback that
// doesn't require rebuilding the VPK. Same engine, same font.
static const Layout LAY_SIMPLE = {
    { "1234567890", "ABCDEFGHIJ", "KLMNOPQRST", "UVWXYZ-_. " },
    { "1234567890", "ABCDEFGHIJ", "KLMNOPQRST", "UVWXYZ-_. " },
    4,
    { "ESPACE", "EFFACER", "ENTREE", "FERMER" },
    { ACT_SPACE, ACT_BACK, ACT_ENTER, ACT_CLOSE },
    4, 0, "simple"
};

// --- geometry -----------------------------------------------------------------
enum { ROW_H = 40, CELL_PAD = 3, ECHO_H = 34, PAD = 6, ECHO_MAX = 40 };

struct State {
    volatile int open;
    volatile int r, c;
    volatile int shift;      // 0 = none, 1 = one-shot, 2 = locked
    volatile int mask;       // 1 = echo as dots (password)
    volatile int simple;     // 1 = legacy layout
    volatile int echo_n;
    char         echo[ECHO_MAX + 1];   // local echo — never logged
};

inline const Layout& layout(const State& s) { return s.simple ? LAY_SIMPLE : LAY_FULL; }

inline int cols(const Layout& L, int r) {
    if (r < 0 || r > L.nrows) return 0;
    return (r < L.nrows) ? (int)strlen(L.lo[r]) : L.nfn;
}
inline int nrows_total(const Layout& L) { return L.nrows + 1; }

inline int panel_h(const Layout& L) {
    return PAD + (L.echo ? (ECHO_H + PAD) : 0) + nrows_total(L) * ROW_H + PAD;
}
inline int panel_y0(const Layout& L, int scr_h) { return scr_h - panel_h(L); }

inline void cell_rect(const Layout& L, int r, int c, int scr_w, int scr_h,
                      int* x, int* y, int* w, int* h) {
    const int n = cols(L, r) > 0 ? cols(L, r) : 1;
    const int cw = scr_w / n;
    *x = c * cw + CELL_PAD;
    *w = cw - 2 * CELL_PAD;
    *y = panel_y0(L, scr_h) + PAD + (L.echo ? (ECHO_H + PAD) : 0) + r * ROW_H;
    *h = ROW_H - 4;
}

// Character displayed (and emitted) by a cell; 0 for the function row or an
// out-of-range cell.
inline char face(const Layout& L, int r, int c, int shift) {
    if (r < 0 || r >= L.nrows) return 0;
    const char* row = shift ? L.up[r] : L.lo[r];
    const int n = (int)strlen(L.lo[r]);
    if (c < 0 || c >= n) return 0;
    if ((int)strlen(row) != n) return 0;      // mismatched tables: nothing rather than wrong
    return row[c];
}

// --- local echo -----------------------------------------------------------
inline void echo_clear(State& s) { memset(s.echo, 0, sizeof s.echo); s.echo_n = 0; }
inline void echo_push(State& s, char ch) {
    int n = s.echo_n;
    if (n < 0 || n > ECHO_MAX) n = 0;
    if (n == ECHO_MAX) {                        // sliding window of the last 40
        memmove(s.echo, s.echo + 1, ECHO_MAX - 1);
        n = ECHO_MAX - 1;
    }
    s.echo[n] = ch; s.echo[n + 1] = 0; s.echo_n = n + 1;
}
inline void echo_pop(State& s) {
    int n = s.echo_n;
    if (n <= 0 || n > ECHO_MAX) { echo_clear(s); return; }
    s.echo[n - 1] = 0; s.echo_n = n - 1;
}

// --- open / close -----------------------------------------------------------
inline void open_kb(State& s, int simple) {
    s.simple = simple ? 1 : 0;
    s.r = 1; s.c = 0; s.shift = 0; s.mask = 0;
    echo_clear(s);
    s.open = 1;
}
inline void close_kb(State& s) {
    s.open = 0;
    echo_clear(s);                 // the password doesn't survive closing
    s.shift = 0; s.mask = 0;
}

// --- navigation ---------------------------------------------------------------
// Changing rows reprojects the column: rows don't have the same key count
// (12, 11, 6), and a plain clamp would stick the selection to the right edge.
// Proportional remapping keeps the key under the thumb where it was.
inline void nav(State& s, int dr, int dc) {
    const Layout& L = layout(s);
    int r = s.r, c = s.c;
    const int nr = nrows_total(L);
    if (r < 0 || r >= nr) r = 0;
    if (dr) {
        const int oldn = cols(L, r) > 0 ? cols(L, r) : 1;
        const int nr2 = ((r + dr) % nr + nr) % nr;
        const int newn = cols(L, nr2) > 0 ? cols(L, nr2) : 1;
        c = (c * newn + oldn / 2) / oldn;
        if (c >= newn) c = newn - 1;
        if (c < 0) c = 0;
        r = nr2;
    }
    if (dc) {
        const int n = cols(L, r) > 0 ? cols(L, r) : 1;
        c = ((c + dc) % n + n) % n;
    }
    s.r = r; s.c = c;
}

// --- cell activation -----------------------------------------------------------
// Pure in that it only writes keyboard state and returns the action; the
// caller (vita_present.cpp) injects into the game. The game thread never
// blocks here.
inline Act activate(State& s, int r, int c, char* out_ch) {
    const Layout& L = layout(s);
    if (out_ch) *out_ch = 0;
    if (r < 0 || r >= nrows_total(L)) return ACT_NONE;
    if (c < 0 || c >= cols(L, r)) return ACT_NONE;
    if (r < L.nrows) {
        const char ch = face(L, r, c, s.shift != 0);
        if (!ch || ch == ' ') return ACT_NONE;
        if (s.shift == 1) s.shift = 0;          // one-shot shift
        echo_push(s, ch);
        if (out_ch) *out_ch = ch;
        return ACT_CHAR;
    }
    switch (L.fnact[c]) {
        case ACT_SHIFT: s.shift = (s.shift + 1) % 3; return ACT_SHIFT;
        case ACT_MASK:  s.mask  = !s.mask;           return ACT_MASK;
        case ACT_SPACE: echo_push(s, ' '); if (out_ch) *out_ch = ' '; return ACT_SPACE;
        case ACT_BACK:  echo_pop(s);                 return ACT_BACK;
        case ACT_ENTER: echo_clear(s);               return ACT_ENTER;
        case ACT_CLOSE: close_kb(s);                 return ACT_CLOSE;
        default: return ACT_NONE;
    }
}

// Direct shift toggle (Square button), same three-state machine.
inline void shift_cycle(State& s) { s.shift = (s.shift + 1) % 3; }
inline void mask_toggle(State& s) { s.mask = !s.mask; }

// --- hit testing ----------------------------------------------------------
// Screen coordinates (960x544). Returns 1 and fills (r,c) if the point falls
// inside a key.
inline int hit(const Layout& L, int scr_w, int scr_h, int px, int py, int* r, int* c) {
    for (int rr = 0; rr < nrows_total(L); ++rr)
        for (int cc = 0; cc < cols(L, rr); ++cc) {
            int x, y, w, h; cell_rect(L, rr, cc, scr_w, scr_h, &x, &y, &w, &h);
            if (px >= x && px < x + w && py >= y && py < y + h) {
                if (r) *r = rr;
                if (c) *c = cc;
                return 1;
            }
        }
    return 0;
}

// --- drawing --------------------------------------------------------------
namespace draw_detail {
// The framebuffer is A8B8G8R8: the low byte is red. Writing 0xFF2060A0 while
// thinking "blue" renders as orange on screen — hence this explicit
// constructor.
inline constexpr uint32_t rgb(uint32_t r, uint32_t g, uint32_t b) {
    return 0xFF000000u | (b << 16) | (g << 8) | r;
}
// alpha in [0,100]: 100 = opaque (default, every pre-existing call site keeps
// today's behaviour unchanged), 0 = invisible. Blended per byte against
// whatever is already in the framebuffer (the game frame, or an earlier
// keyboard shape drawn this same call — layers compose the way a translucent
// overlay is expected to), alpha channel always written back as 0xFF since
// this is the final scanout buffer, not an intermediate compositing surface.
inline uint32_t blend(uint32_t dst, uint32_t v, int alpha) {
    if (alpha >= 100) return v;
    if (alpha <= 0)   return dst;
    const uint32_t a = (uint32_t)alpha, ia = 100u - a;
    uint32_t out = 0xFF000000u;
    for (int shift = 0; shift <= 16; shift += 8) {
        const uint32_t s = (v >> shift) & 0xFFu, d = (dst >> shift) & 0xFFu;
        out |= ((s * a + d * ia) / 100u) << shift;
    }
    return out;
}
inline void px(uint32_t* fb, int W, int H, int x, int y, uint32_t v, int alpha = 100) {
    if (x >= 0 && x < W && y >= 0 && y < H) {
        uint32_t& d = fb[(size_t)y * W + x];
        d = (alpha >= 100) ? v : blend(d, v, alpha);
    }
}
inline void rect(uint32_t* fb, int W, int H, int x, int y, int w, int h, uint32_t v, int alpha = 100) {
    for (int yy = y; yy < y + h; ++yy)
        for (int xx = x; xx < x + w; ++xx) px(fb, W, H, xx, yy, v, alpha);
}
inline void frame(uint32_t* fb, int W, int H, int x, int y, int w, int h, uint32_t v, int alpha = 100) {
    for (int xx = x; xx < x + w; ++xx) { px(fb, W, H, xx, y, v, alpha); px(fb, W, H, xx, y + h - 1, v, alpha); }
    for (int yy = y; yy < y + h; ++yy) { px(fb, W, H, x, yy, v, alpha); px(fb, W, H, x + w - 1, yy, v, alpha); }
}
inline void ch(uint32_t* fb, int W, int H, char c, int x, int y, int sc, uint32_t v, int alpha = 100) {
    const unsigned char* g = glyph(c);
    if (!g) return;
    for (int gy = 0; gy < 16; ++gy)
        for (int gx = 0; gx < 8; ++gx)
            if (g[gy] & (0x80 >> gx))
                for (int sy = 0; sy < sc; ++sy)
                    for (int sx = 0; sx < sc; ++sx)
                        px(fb, W, H, x + gx * sc + sx, y + gy * sc + sy, v, alpha);
}
inline void text(uint32_t* fb, int W, int H, const char* t, int x, int y, int sc, uint32_t v, int alpha = 100) {
    for (int i = 0; t[i]; ++i) ch(fb, W, H, t[i], x + i * 8 * sc, y, sc, v, alpha);
}
inline void dot(uint32_t* fb, int W, int H, int x, int y, uint32_t v, int alpha = 100) {   // masked-mode dot
    static const unsigned char d[8] = { 0x3c, 0x7e, 0xff, 0xff, 0xff, 0xff, 0x7e, 0x3c };
    for (int gy = 0; gy < 8; ++gy)
        for (int gx = 0; gx < 8; ++gx)
            if (d[gy] & (0x80 >> gx))
                for (int sy = 0; sy < 2; ++sy)
                    for (int sx = 0; sx < 2; ++sx)
                        px(fb, W, H, x + gx * 2 + sx, y + gy * 2 + sy, v, alpha);
}
} // namespace draw_detail

// Draws nothing when the keyboard is closed — the check is duplicated here
// and in the caller: a closed keyboard leaving a trace on screen would be a
// permanent display glitch.
//
// alpha (0-100, default 100 = opaque): every existing caller keeps today's
// look with zero source changes; a caller that wants to still see the game
// behind the keyboard passes a lower value (e.g. 50).
inline void draw(const State& s, uint32_t* fb, int scr_w, int scr_h, int alpha = 100) {
    using namespace draw_detail;
    if (!fb || !s.open) return;
    const Layout& L = layout(s);
    const int y0 = panel_y0(L, scr_h);
    if (y0 < 0) return;
    rect(fb, scr_w, scr_h, 0, y0, scr_w, scr_h - y0, rgb(0x18,0x18,0x18), alpha);

    if (L.echo) {
        const int ex = 8, ey = y0 + PAD, ew = scr_w - 16, eh = ECHO_H;
        rect(fb, scr_w, scr_h, ex, ey, ew, eh, rgb(0x0C,0x0C,0x0C), alpha);
        frame(fb, scr_w, scr_h, ex, ey, ew, eh, rgb(0x50,0x50,0x50), alpha);
        int n = s.echo_n; if (n < 0) n = 0; if (n > ECHO_MAX) n = ECHO_MAX;
        for (int i = 0; i < n; ++i) {
            const int cx = ex + 6 + i * 16, cy = ey + (eh - 32) / 2;
            if (s.mask) dot(fb, scr_w, scr_h, cx, cy + 8, rgb(0xC0,0xC0,0xC0), alpha);
            else        ch(fb, scr_w, scr_h, s.echo[i], cx, cy, 2, rgb(0xE0,0xE0,0xE0), alpha);
        }
        // caret
        rect(fb, scr_w, scr_h, ex + 6 + n * 16, ey + 6, 2, eh - 12, rgb(0xFF,0xC0,0x40), alpha);
    }

    for (int r = 0; r < nrows_total(L); ++r) {
        const int nc = cols(L, r);
        for (int c = 0; c < nc; ++c) {
            int x, y, w, h; cell_rect(L, r, c, scr_w, scr_h, &x, &y, &w, &h);
            const bool sel = (r == s.r && c == s.c);
            const bool fnrow = (r >= L.nrows);
            bool armed = false;
            if (fnrow) {
                if (L.fnact[c] == ACT_SHIFT && s.shift) armed = true;
                if (L.fnact[c] == ACT_MASK  && s.mask)  armed = true;
            }
            uint32_t fill = fnrow ? rgb(0x26,0x26,0x26) : rgb(0x30,0x30,0x30);
            if (armed) fill = rgb(0xC0,0x80,0x10);          // engaged modifier: amber
            if (sel)   fill = rgb(0x20,0x70,0xC0);          // selection: blue
            rect(fb, scr_w, scr_h, x, y, w, h, fill, alpha);
            if (sel) frame(fb, scr_w, scr_h, x, y, w, h, rgb(0xFF,0xFF,0xFF), alpha);
            if (!fnrow) {
                const char f = face(L, r, c, s.shift != 0);
                if (f && f != ' ') ch(fb, scr_w, scr_h, f, x + (w - 16) / 2, y + (h - 32) / 2, 2, rgb(0xFF,0xFF,0xFF), alpha);
            } else {
                const char* t = L.fn[c];
                const int n = (int)strlen(t);
                text(fb, scr_w, scr_h, t, x + (w - n * 8) / 2, y + (h - 16) / 2, 1, rgb(0xFF,0xFF,0xFF), alpha);
                if (L.fnact[c] == ACT_SHIFT && s.shift == 2)     // shift locked: underline bar
                    rect(fb, scr_w, scr_h, x + 6, y + h - 6, w - 12, 3, rgb(0xFF,0xFF,0xFF), alpha);
            }
        }
    }
}

} // namespace d2kb
#endif // D2VITA_VITA_KB_H
